### ISSUE TITLE
[Fix] Tweak multiple word Element titles

### ISSUE THREAD

**Issue by usernamehw** [ryanraposo/codeui#15]
Probably could be improved by deleting more from the start:

|    Expected     |   Actual        |
| ------------- |-------------|
|   `Activity Bar` => `Badge Background`    | `Activity Bar` => `Barbadge Background`  |
| `Peek View` => `Border` | `Peek View` => `View Border` |
| `Welcome Page` => `Button Background` | `Welcome Page` => `Page Button Background` |
| ... | ... |

1-word titles are all looking great though.

**Comment by ryanraposo** [comment]
It’s an external python script I wrote to rip them from the MS doc about theme colors and build a Json like in /data. I’ll look after this, I think there’s a new element also so it needs doing

**Comment by ryanraposo** [comment]
Made a healthy attempt to address in #22

**Comment by ryanraposo** [comment]
There should only be a few odd instances left, we'll use new issues to catch them
